name: flutter_boilerplate
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  intl: ^0.17.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_name:
    git:
      url: https://github.com/ride4sun/flutter_launcher_name
      ref: 0.9.1
  flutter_launcher_icons: ^0.9.0
  lint: ^1.0.0
  rename: ^1.3.1

# You can change the app_name from here
flutter_launcher_name:
  name: 'FT Boilerplate'

# You can change the app_icon from here
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/icon/app-icon.png'
  # adaptive_icon_foreground: 'assets/image/icons/app-icon-adaptive.png'
  adaptive_icon_background: '#FFFF'

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/icon/
    - assets/images/logo/
    - assets/images/ilustration/
    # - assets/images/emoji/
    # - assets/images/landing_page/

  # Set list app_fonts
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
